import "./globals.css";
import type { Metadata } from "next";
import { Italiana } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";

const italiana = Italiana({
  weight: "400",
  variable: "--font-italiana",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${italiana.variable}  bg-stone-200 h-screen`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
