import "./globals.css";
import type { Metadata } from "next";
import { Italiana } from "next/font/google";

const italiana = Italiana({
  weight: "400",
  variable: "--font-italiana",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* border section */}
      <div className="w-screen  left-0 top-0 fixed">
        <div className="left-0 top-0 h-[50px] border-r-black border-2  bg-stone-200" />
      </div>
      <div className="w-[50px] h-screen left-0 top-0 fixed ">
        <div className="left-0 top-0 relative min-h-screen border-r-black border-2  bg-stone-200" />
        <div className="left-[10px] absolute top-[50%] bg-stone-200 origin-top-left -rotate-90 text-black text-2xl ">
          2regards
        </div>
      </div>
      <div className="fixed left-[100px] bottom-0 justify-start items-start gap-14 inline-flex">
        <div className="text-black text-[17px] font-normal leading-loose">
          Products
        </div>
        <div className="text-black text-[17px] font-normal leading-loose">
          Studio
        </div>
        <div className="text-black text-[17px] font-normal leading-loose">
          Gallery
        </div>
        <div className="text-black text-[17px] font-normal leading-loose">
          About
        </div>
        <div className="text-black text-[17px] font-normal leading-loose">
          Contact
        </div>
      </div>
      <body className={`${italiana.variable}  bg-stone-200`}>{children}</body>
    </html>
  );
}
